### ISSUE TITLE
RefreshDatabaseTrait is deprecated

### ISSUE THREAD

**Issue by erwanflr** [theofidry/AliceBundle#13]
Hi,

I am having the following error when using RefreshDatabaseTrait in my tests suite:
Doctrine\ORM\Exception\NotSupported: Feature was deprecated in doctrine/dbal 2.x and is not supported by installed doctrine/dbal:3.x, please see the doctrine/deprecations logs for new alternative approaches.

Any idea what could be a good workaround?

Thanks!

**Comment by theofidry** [comment]
Hi, unfortunately I cannot say without any more logs... I do not know from where this exception is thrown neither why
