### ISSUE TITLE
Clear entity manager

### ISSUE THREAD

**Issue by ro0NL** [theofidry/AliceBundle#15]
We have an issue with fixtures being loaded before running a test (`RefreshDatabaseTrait`). Some entity does not update the inverse side at runtime ...

In prod env the collection on the inverse side is lazy loaded, so no issues ...

In test env the collection remains empty, causing the test to fail (but only if it runs first, eg. `bin/phpunit SpecificTest.php`).

Invoking `$container->get('doctine')->getManager()->clear()` after fixtures are loaded solves it. IMHO this makes the testsuite more deterministic (i only noticed when running some test isolated).

Would you consider a PR for that?

**Comment by theofidry** [comment]
Hi @ro0NL!

IIRC there was a time where `clear()` was considered and used but got quickly reverted because if you pass some existing objects, then those gets detached and would need to be attached again...

So I am not entirely sure on how to solve this... Maybe it would possible to have a clear and re-attach the entities but that feels a bit wonky especially since there is no knowing which entity manager to use to re-attach them

**Comment by ro0NL** [comment]
well, from a phpunit testcase POV im not passing "existing objects" at all

All i do is let the bundle persist from yaml fixture files before each test (RefreshDatabaseTrait)

AFAIK after loading fixtures, and before starting the test, it should be safe to clear EM.

**Comment by ro0NL** [comment]
OH, i figured we hook into `bootKernel`, not `setUp`

so IIUC there could be a case doctrine already has some attached entiies before booting the kernel ... then we're stuck on current API :)

**Comment by theofidry** [comment]
Wouldn't to be possible to add a decorator to do a clear automatically in your case? I'm also not sure to understand why you have clear-based actions either. Shouldn't everything be handled by flush?

**Comment by ro0NL** [comment]
i can invoke `$container->get('doctine')->getManager()->clear()` after invoking [`createClient`](https://github.com/symfony/symfony/blob/057844d0363be7623f4ea7cb482e301c99460de2/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php#L38) for affected testcases only ...

or just run the testsuite as a whole :)

> I'm also not sure to understand why you have clear-based actions either. Shouldn't everything be handled by flush?

This bundle factorizes the entities from yaml, and flushes them (it works fine). I guess the EM keeps re-using those exact same objects. 

Given the entity constructor initializes `new ArrayCollection()` it's considered empty (until we clear()), whereas in production the entity would be loaded from DB directly, and thus lazy loads this collection.

This is argueably a design issue on my side; not updating the inverse side introduces invalid state. A state which doesnt occur in prod though :')
