### ISSUE TITLE
bin/console hautelook:fixtures:load for only data base test

### ISSUE THREAD

**Issue by ziat1988** [theofidry/AliceBundle#18]
Hello,
First of all, thanks for the awsome bundle.
I actually use two database in dev mode: one for dev (same as database in production) and other is real data in test.
When I run `bin/console hautelook:fixtures:load` it purge my database dev. 
What I want is it affect only my database test. If there's a way in a config file to do that ?
Thanks a lot

**Comment by theofidry** [comment]
Hi, passing the environment variable should be enough to achieve that. If it's not it would either mean that your test connection is the same as the dev one or that there is a bug somewhere
