### ISSUE TITLE
Symfony 6 compatibility

### ISSUE THREAD

**Issue by metaer** [theofidry/AliceBundle#3]

**Comment by tacman** [comment]
I made some of the easy changes for Symfony 6 support, mostly fixing the method signatures to include typehints.

But I'm not sure how to set up the database for testing.  I'm getting a failure when running phpunit that is almost certainly related to my testing environment and not some issue in the code, which I think will be pretty easy to make compatible with Symfony 6.

**Comment by theofidry** [comment]
Fixed with the new release
