### ISSUE TITLE
Support fixtures in JSON format

### ISSUE THREAD

**Issue by ziwot** [theofidry/AliceBundle#31]
Json files are currently not detected

https://github.com/nelmio/alice/blob/master/doc/complete-reference.md#json

It seems we just need to add `json` here, but maybe there's more to do? (beyond adding tests)
https://github.com/theofidry/AliceBundle/blob/master/src/Locator/EnvDirectoryLocator.php#L86

**Comment by theofidry** [comment]
Ha indeed probably, I guess I never saw JSON fixtures 😅
