### ISSUE TITLE
Load only specific fixtures files in test

### ISSUE THREAD

**Issue by KBS-pmateusz** [theofidry/AliceBundle#33]
Hi,

First of all, thank you for the awesome bundle!

I know that fixtures files are loaded automatically based on the hautelook_alice.yaml config and you can load different fixture definitions per environment but when there is a lot of logic putting all fixture definitions into a single yaml file can be a bit hard to manage.

Is there a way to load only specific yaml/php fixtures files for in a test class?

I'm specifically looking for something like this:

```php
/**
 * Class ProductControllerTest
 *
 * @package App\Tests\Controller
 */
class ProductControllerTest extends WebTestCase
{

    use ReloadDatabaseTrait;

    /**
     * {@inheritdoc}
     */
    protected function setUp(): void
    {
        // define fixtures files to load.
        self::$fixtures = ['auth.yaml', 'ordered_products.yaml'];

        parent::setUp(); // populates database with fixtures from self::$fixtures only.
    }

...
}
```

Thanks in advance!

**Comment by theofidry** [comment]
Hi!

IMO (there is more details [here](https://github.com/theofidry/AliceBundle#when-to-use-this-bundle)), if you don't need the fixtures auto-discovery, you are better of using the underlying AliceDataFixtures library directly: https://github.com/theofidry/AliceDataFixtures/blob/master/doc/advanced-usage.md#phpunit

**Comment by KBS-pmateusz** [comment]
Hi,

I must have missed that there is AliceDataFixtures completely. This should work great.

I really appreciate you for taking time to answer, thank you!
