### ISSUE TITLE
There are no commands defined in the "hautelook:fixtures" namespace

### ISSUE THREAD

**Issue by logosur** [theofidry/AliceBundle#46]
Hello,

I've just installed the bundle, and the command php bin/console hautelook:fixtures:load is throwing the error:
There are no commands defined in the "hautelook:fixtures" namespace

It seems that the issue is existing since three months at least:
https://stackoverflow.com/questions/76563869/error-in-loading-fixtures-on-symfony-with-hautelook-alicebundle

`                                                                                                                        
 [WARNING] Some commands could not be registered:                                                                       
                                                                                                                        

In DoctrineOrmLoadDataFixturesCommand.php line 41:
                                                                                                                                      
  [TypeError]                                                                                                                         
  Argument 2 passed to Hautelook\AliceBundle\Console\Command\Doctrine\DoctrineOrmLoadDataFixturesCommand::__construct() must be an i  
  nstance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bundle\DoctrineBundle\Registry given, called in /app/  
  var/cache/dev/ContainerX0vuky0/getHautelookAlice_Console_Command_Doctrine_DoctrineOrmLoadDataFixturesCommandService.php on line 23  
                                                                                                                                      

Exception trace:
  at /app/vendor/hautelook/alice-bundle/src/Console/Command/Doctrine/DoctrineOrmLoadDataFixturesCommand.php:41
 Hautelook\AliceBundle\Console\Command\Doctrine\DoctrineOrmLoadDataFixturesCommand->__construct() at /app/var/cache/dev/ContainerX0vuky0/getHautelookAlice_Console_Command_Doctrine_DoctrineOrmLoadDataFixturesCommandService.php:23
 ContainerX0vuky0\getHautelookAlice_Console_Command_Doctrine_DoctrineOrmLoadDataFixturesCommandService::do() at /app/var/cache/dev/ContainerX0vuky0/App_KernelDevDebugContainer.php:426
 ContainerX0vuky0\App_KernelDevDebugContainer->load() at /app/vendor/symfony/dependency-injection/Container.php:238
 Symfony\Component\DependencyInjection\Container->make() at /app/vendor/symfony/dependency-injection/Container.php:220
 Symfony\Component\DependencyInjection\Container->get() at /app/vendor/symfony/framework-bundle/Console/Application.php:191
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /app/vendor/symfony/framework-bundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /app/bin/console:43`

PHP 7.4
Symfony 5.4.27

Thanks!

**Comment by logosur** [comment]
Fixed changing this line:
vendor/hautelook/alice-bundle/src/Console/Command/Doctrine/DoctrineOrmLoadDataFixturesCommand.php:14
use Doctrine\Common\Persistence\ManagerRegistry;
by
use Doctrine\Persistence\ManagerRegistry;

**Comment by theofidry** [comment]
>Fixed changing this line:
>vendor/hautelook/alice-bundle/src/Console/Command/Doctrine/DoctrineOrmLoadDataFixturesCommand.php:14
>use Doctrine\Common\Persistence\ManagerRegistry;
>by
>use Doctrine\Persistence\ManagerRegistry;

This is already the case since 2.6.1 so it is actually already fixed.
