### ISSUE TITLE
Drop compatibility with unsupported versions of Symfony and PHP

### ISSUE THREAD

**Issue by tacman** [theofidry/AliceBundle#5]
Currently the bundle allows for very old and unsupported versions of Symfony.  Is there any benefit to dropping that, especially since we'll be adding Symfony 6 support (#3)

        "symfony/finder": "^3.4 || ^4.0 || ^5.0",
        "symfony/framework-bundle": "^3.4.24 || ^4.0 || ^5.0",

Maybe there's no benefit to dropping support for before 4.4, but I'd hate to see improvements being held back because of support for unsupported versions.

Ditto on support for 7.3, so the bundle can use some features from 7.4.

Thoughts?

**Comment by bertrandseurot** [comment]
Note : nelmio/alice already requires php 7.4

**Comment by theofidry** [comment]
Fixed with the new release
