### ISSUE TITLE
Call to a member function getSQLLogger() on null

### ISSUE THREAD

**Issue by Helo3615** [theofidry/AliceBundle#6]
Hi, 

I have recently updated symfony and some packages and when I try to launch fixtures with `console h:f:l --env=test --no-interaction --purge-with-truncate` the folowing error occurs :

```
app.INFO: fixtures found {"files":["...x.yaml"]} []
app.INFO: Purging database with purge mode "TRUNCATE_MODE". [] []
app.INFO: Loading fixtures. [] []
app.INFO: Pre-processing objects. [] []
app.INFO: Flushing objects. [] []
php.CRITICAL: Uncaught Error: Call to a member function getSQLLogger() on null {"exception":"[object] (Error(code: 0): Call to a member function getSQLLogger() on null at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1513)"} []
```

I am using : 
- Symfony 5.4
- Doctrine\ORM 2.10
- hautelook\alice-bundle 2.9

fixtures.yaml :
```
hautelook_alice:
  fixtures_path: 'fixtures'
  root_dirs:
    - '%kernel.project_dir%'
```

**If I remove the logger part in `/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php::executeStatement()` which is causing the error everything works fine.**

Let me know if you need further information.

Thanks you

**Comment by theofidry** [comment]
Should be fixed with the new release

**Comment by ptondereau** [comment]
Hello @theofidry! Can we please have the code's update that caused that in detail?
